name: "Debug-It"
description: "Connect to the GitHub Actions runner via SSH/RDP/VNC."

inputs:
  tenant-id:
    description: "Azure Entra Tenant Id"
    required: true
  client-id:
    description: "Azure Entra Client Id"
    required: true
  authorized-user:
    description: "User authorized to access the runner"
    required: false
  ports:
    description: "Comma delimited list of ports to be forwarded"
    required: false
    default: "22"
  expiry:
    description: "Devtunnel expiry"
    required: false
    default: "1h"
runs:
  using: "composite"
  steps:
    - name: Add SSH keys
      shell: bash
      run: |
        SSH_KEYS_URL="https://github.com/${AUTHORIZED_USER:-$CURRENT_USER}.keys"
        echo "Setting public keys from $SSH_KEYS_URL"
        mkdir -p ~/.ssh
        touch ~/.ssh/authorized_keys
        curl $SSH_KEYS_URL >> ~/.ssh/authorized_keys
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/authorized_keys
      env:
        AUTHORIZED_USER: ${{ inputs.authorized-user }}
        CURRENT_USER: ${{ github.actor }}

    - name: Install DevTunnel CLI
      id: install
      shell: bash
      run: |
        curl -sL https://aka.ms/DevTunnelCliInstall | bash
        echo "pathname=$HOME/bin/devtunnel" >> $GITHUB_OUTPUT

    - name: Login to DevTunnels
      shell: bash
      run: |
        OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r .value)
        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" == "null" ]; then
          echo "::error::Failed to retrieve OIDC token."
          exit 1
        fi

        $DEVTUNNEL user login --entra --sp-tenant-id $TENANT_ID --sp-client-id $CLIENT_ID --federated-token "$OIDC_TOKEN"
      env:
        DEVTUNNEL: ${{ steps.install.outputs.pathname }}
        TENANT_ID: ${{ inputs.tenant-id }}
        CLIENT_ID: ${{ inputs.client-id }}

    - name: Start DevTunnel
      shell: bash
      run: |
        PORTS=$(echo "$PORTS" | sed 's/,/ -p /g; s/^/-p /')
        echo "$DEVTUNNEL host $PORTS --expiration $EXPIRY --allow-anonymous"
      env:
        DEVTUNNEL: ${{ steps.install.outputs.pathname }}
        PORTS: ${{ inputs.ports }}
        EXPIRY: ${{ inputs.expiry}}
