name: "Debug-It"
description: "Connect to the GitHub Actions runner via SSH/RDP/VNC."

inputs:
  authorized-user:
    description: "User authorized to access the runner"
    required: false
  ports:
    description: "Comma delimited list of ports to be forwarded"
    required: false
    default: "22"
  expiry:
    description: "Devtunnel expiry"
    required: false
    default: "1h"
  new-password:
    description: "Reset user password for the RDP/VNC connection"
    required: false
runs:
  using: "composite"
  steps:
    - name: Check permissions
      shell: bash
      run: |
        EXPECTED_USER=${AUTHORIZED_USER:-$CURRENT_USER}
        PERMISSION=$(gh api /repos/$REPO_NWO/collaborators/$EXPECTED_USER/permission | jq -r ".permission")
        if [ "$PERMISSION" != "admin" ]; then
          echo "Must be repo admin to debug the job"
          exit 1
        fi
      env:
        AUTHORIZED_USER: ${{ inputs.authorized-user }}
        CURRENT_USER: ${{ github.actor }}
        REPO_NWO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}

    - name: Add SSH keys
      shell: bash
      run: |
        SSH_KEYS_URL="https://github.com/${AUTHORIZED_USER:-$CURRENT_USER}.keys"
        echo "Setting public keys from $SSH_KEYS_URL"
        mkdir -p ~/.ssh
        touch ~/.ssh/authorized_keys
        curl $SSH_KEYS_URL >> ~/.ssh/authorized_keys
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/authorized_keys
      env:
        AUTHORIZED_USER: ${{ inputs.authorized-user }}
        CURRENT_USER: ${{ github.actor }}

    - name: Configure SSH permissions (windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        cp "$HOME\.ssh\authorized_keys" "$env:ProgramData\ssh\administrators_authorized_keys"
        icacls "$env:ProgramData\ssh\administrators_authorized_keys" /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F"

    - name: Prepare RDP
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        if ($env:NEW_PASSWORD -ne '') {
          $userPasswordSecure = ConvertTo-SecureString $env:NEW_PASSWORD -AsPlainText -Force
          Set-LocalUser -Name $env:USERNAME -Password $userPasswordSecure
        }

        $regPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'
        $regName = 'fSingleSessionPerUser'
        $regValue = 0

        if (-not (Test-Path $regPath)) {
          New-Item -Path $regPath -Force | Out-Null
        }

        New-ItemProperty -Path $regPath -Name $regName -PropertyType DWord -Value $regValue -Force
      env:
        NEW_PASSWORD: ${{ inputs.new-password }}

    - name: Prepare VNC
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist

        epoch="$(date +%s)"
        sudo sqlite3 "${DB_PATH}" \
          "BEGIN TRANSACTION; \
           DELETE FROM access WHERE client = 'com.apple.screensharing.agent'; \
           COMMIT; \
           BEGIN TRANSACTION; \
           INSERT INTO access(service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier_type,flags,last_modified,last_reminded) VALUES('kTCCServicePostEvent','com.apple.screensharing.agent',0,2,4,1,0,0,${epoch},${epoch}); \
           INSERT INTO access(service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier_type,flags,last_modified,last_reminded) VALUES('kTCCServiceScreenCapture','com.apple.screensharing.agent',0,2,4,1,0,0,${epoch},${epoch}); \
           COMMIT;"
      env:
        DB_PATH: "/Library/Application Support/com.apple.TCC/TCC.db"

    - name: Install DevTunnel CLI (windows)
      id: install-win
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        mkdir -p $HOME/bin
        curl -sL -o $HOME/bin/devtunnel.exe https://aka.ms/TunnelsCliDownload/win-x64
        echo "pathname=$HOME/bin/devtunnel.exe" >> $GITHUB_OUTPUT

    - name: Install DevTunnel CLI (linux, macOS)
      id: install-other
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        curl -sL https://aka.ms/DevTunnelCliInstall | bash
        echo "pathname=$HOME/bin/devtunnel" >> $GITHUB_OUTPUT

    - name: Set context
      id: install
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          echo "pathname=${{ steps.install-win.outputs.pathname }}" >> $GITHUB_OUTPUT
        else
          echo "pathname=${{ steps.install-other.outputs.pathname }}" >> $GITHUB_OUTPUT
        fi

    - name: Login to DevTunnels
      shell: bash
      run: |
        $DEVTUNNEL user login --github --use-device-code-auth

        LOGGED_USER=$($DEVTUNNEL user show --json | jq -r ".username")
        EXPECTED_USER=${AUTHORIZED_USER:-$CURRENT_USER}
        if [ "$LOGGED_USER" != "$EXPECTED_USER" ]; then
          echo "Must login as $EXPECTED_USER"
          exit 1
        fi
      env:
        DEVTUNNEL: ${{ steps.install.outputs.pathname }}
        AUTHORIZED_USER: ${{ inputs.authorized-user }}
        CURRENT_USER: ${{ github.actor }}

    - name: Start DevTunnel
      shell: bash
      run: |
        PORTS=$(echo "$PORTS" | sed 's/,/ -p /g; s/^/-p /')
        $DEVTUNNEL host $PORTS --expiration $EXPIRY
      env:
        DEVTUNNEL: ${{ steps.install.outputs.pathname }}
        PORTS: ${{ inputs.ports }}
        EXPIRY: ${{ inputs.expiry}}
